# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: RY 's Blog
subtitle: The best way out is always through
author: RY Zheng
language: en 
timezone: Asia/Singapore
keywords: iOS, YOLO, react-native

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://suelan.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

sidebar-avatar: img/avatar.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`

# Friends
# 友情链接
#friends: [
#    {
#        title: "10000H",
#        href: "https://www.10000h.top"
#    },{
#        title: "Xiaotao's Page",
#        href: "https://niexiaotao.com"
#    },{
#        title: "It helps SEO",
#        href: "#"
#    }
#]

#comment:
#  type: gitment
#  id: your-id-created-by-https://github.com/settings/applications/new
#  secret: your-secret-created-by-https://github.com/settings/applications/new
#  owner: aircloud
#  repo: hexo-aircloud-blog

#comment:
#   type: disqus
#   script: 'https://airclouds-blog.disqus.com/embed.js'

donate:
  img: img/donate.jpeg
  content: Buy me a cup of coffee 

# The following content is not recommended to modify
# 搜索数据文件路径设置，不建议改动：
search:
  path: search.json
  field: post

# Custom Setting End
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: 4
  wrap: true

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: bmw

# Deployment
## Docs: https://hexo.io/docs/deployment.html
# deploy:
#   type: git 
#   repo: https://github.com/sueLan/sueLan.github.io
#   email: scutryzheng@gmail.com
#   branch: master

## indent
post_style:
    indent: 0
