# 更多细节请参考 demo: https://github.com/dongyuanxin/theme-bmw/blob/master/demo._config.yml
keywords: Hexo, theme-bmw

# 站点图标和APP图标
favicon: 
  icon: /img/favicon.ico
  touch_icon: /img/favicon.ico

# RSS文件位置
rss: 
  /rss/atom.xml
# 自定义样式文件位置
custom_style: 

# 自定义脚本：支持自定义多个脚本文件
# src: 文件位置
# load: <script>加载方式(async/defer/默认)
custom_script: 
  # - 
  #   src: 
  #   load: 
  # - 
  #   src: 
  #   load:

# 是否渲染 文章目录
toc: true

# 是否支持 数学公式
mathjax: true

# 是否开启 音乐组件
player: true

# 是否开启 分享功能: https://github.com/overtrue/share.js
social_share:
  enable: true
  sites: google, facebook, twitter, weibo, wechat, douban 
  disabled: 

# 是否开启 打赏功能
reward: 
  enable: true
  meta: Buy me a cup of coffee # 提示文字
  button_meta: 赞赏 ☕️ # 按钮文字
  qrcodes: 
    # 支持多个支付方式
    # src: 二维码位置
    # meta: 二维码提示信息
    -
      src: /img/donate.jpeg
      meta: "Thank you"
 


# 是否开启版权声明
# author: 您的名字
# license: 声明信息(支持html)
copyright: 
  enable: true
  author: RY Zheng 
  license: 'MIT'

# 页脚信息 
# start: 建站时间. 格式：YYYY-MM-DD
# more: 自定义页脚信息(支持HTML)
footer: 
  start: '2019-03-10'
  more: To see a World in a Grain of Sand;And a Heaven in a Wild Flower; Hold Infinity in the palm of your hand; And Eternity in an hour

# 如何开启 评论&统计 插件：https://godbmw.com/passages/2018-11-15-theme-bmw-docs-zh/
# 请申请自己的 appid 和 appkey，并且替换下面的 appid 和 appkey
leancloud:
    appid: pyVXg5NFiE5JcCDYwumMNjlB-gzGzoHsz # 填写您的appid
    appkey: W9uovU160HsQkI3hQwlHgBqa # 填写您的appkey
    comment: true # 是否开启评论系统
    timer: true # 是否开启文章统计

# 导航栏头部名称
nav_name: RY 

# 导航栏选项
# blank: 是否在新页面打开，默认 false
# children：开启二级导航栏
nav: 
  - 
    name: Home 
    path: /
  -
    name: Popular 
    path: /archives/
  -
    name: Categories 
    path: /categories/
  -
    name: Tags
    path: /tags/
  - 
    name: Me
    children:
      -
        name: Github
        path: "https://github.com/sueLan"
        blank: true
      -
        name: StackOverflow
        path: "https://stackoverflow.com/users/4026902/ry-zheng"
        blank: true
      -
        name: Jian Shu | Chinese
        path: "https://www.jianshu.com/u/23bd8d4cc8bf"
        blank: true
  - 
    name: RSS 
    path: /rss/atom.xml
       

# 友链详细信息：支持多个友链
friends:
  -
    nickname: 蓝容
    avatar:  https://suelan.github.io/img/avatar.jpeg # 头像链接
    site: https://www.jianshu.com/u/23bd8d4cc8bf # 站点地址
    meta: To see a World in a Grain of Sand;And a Heaven in a Wild Flower; Hold Infinity in the palm of your hand; And Eternity in an hour 
    
   